<a href="https://colab.research.google.com/github/aguilarmadeira/CIO/blob/main/AHP_3criterios_5alternativas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

def calculate_priority_vector(A):
    eigvals, eigvecs = np.linalg.eig(A)
    max_eigval = np.max(np.abs(eigvals))
    max_eigvec = np.abs(eigvecs[:, np.argmax(np.abs(eigvals))])
    priority_vector = max_eigvec / np.sum(max_eigvec)

    n = A.shape[0]
    CI = (max_eigval - n) / (n - 1)
    RI = [0, 0, 0.58, 0.90, 1.12, 1.24, 1.32, 1.41, 1.45, 1.49, 1.51, 1.48, 1.56, 1.57, 1.59]
    CR = CI / RI[n-1] if n-1 < len(RI) else None

    print(f'Priority Vector for current matrix:\n{priority_vector}')
    print(f'Max Eigenvalue (maxEig): {max_eigval}')
    print(f'Consistency Index (CI): {CI}')
    print(f'Consistency Ratio (CR): {CR}\n')

    return priority_vector, CR

# Example matrices
criteria_matrix = np.array([
    [1, 2, 0.5],
    [0.5, 1, 0.333],
    [2, 3, 1]
])

comparison_matrix_custo = np.array([
    [1, 1/3, 5, 2, 0.25],
    [3, 1, 7, 3, 0.5],
    [0.2, 0.143, 1, 0.333, 0.125],
    [0.5, 0.333, 3, 1, 0.333],
    [4, 2, 8, 3, 1]
])

comparison_matrix_qualidade = np.array([
    [1, 4, 0.5, 3, 7],
    [0.25, 1, 0.2, 0.5, 3],
    [2, 5, 1, 4, 9],
    [0.333, 2, 0.25, 1, 5],
    [0.143, 0.333, 0.111, 0.2, 1]
])

comparison_matrix_tempo = np.array([
    [1, 3, 0.5, 2, 2],
    [0.333, 1, 0.25, 0.5, 0.5],
    [2, 4, 1, 3, 3],
    [0.5, 2, 0.333, 1, 1],
    [0.5, 2, 0.333, 1, 1]
])

# Calculate priority vectors and CRs
priority_criteria, CR_criteria = calculate_priority_vector(criteria_matrix)
priority_custo, CR_custo = calculate_priority_vector(comparison_matrix_custo)
priority_qualidade, CR_qualidade = calculate_priority_vector(comparison_matrix_qualidade)
priority_tempo, CR_tempo = calculate_priority_vector(comparison_matrix_tempo)

# Aggregate the results
final_scores = (priority_criteria[0] * priority_custo +
                priority_criteria[1] * priority_qualidade +
                priority_criteria[2] * priority_tempo)

print('Final Scores for Alternatives:')
print(final_scores)

# Identify the best alternative
best_index = np.argmax(final_scores) + 1  # Adding 1 to convert 0-based index to 1-based
best_score = final_scores[best_index - 1]
print(f'The best alternative is Alternative {best_index} with a score of {best_score:.4f}.')


Priority Vector for current matrix:
[0.29697472 0.16337387 0.53965141]
Max Eigenvalue (maxEig): 3.0088357831131747
Consistency Index (CI): 0.004417891556587339
Consistency Ratio (CR): 0.007617054407909205

Priority Vector for current matrix:
[0.14349653 0.29188247 0.03786998 0.10195781 0.4247932 ]
Max Eigenvalue (maxEig): 5.1586926283092325
Consistency Index (CI): 0.03967315707730812
Consistency Ratio (CR): 0.03542246167616796

Priority Vector for current matrix:
[0.29437147 0.08236909 0.45271481 0.13485116 0.03569347]
Max Eigenvalue (maxEig): 5.111273104926623
Consistency Index (CI): 0.02781827623165567
Consistency Ratio (CR): 0.024837746635406846

Priority Vector for current matrix:
[0.24441837 0.07907583 0.4030787  0.13671355 0.13671355]
Max Eigenvalue (maxEig): 5.032516120864598
Consistency Index (CI): 0.008129030216149413
Consistency Ratio (CR): 0.007258062692990547

Final Scores for Alternatives:
[0.22260817 0.14281205 0.30273019 0.12608771 0.20576188]
The best alternative is Alt