<a href="https://colab.research.google.com/github/aguilarmadeira/CIO/blob/main/AHP_3criterios_5alternativas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

def normalizar_matriz(matriz):
    soma_colunas = np.sum(matriz, axis=0)
    matriz_normalizada = matriz / soma_colunas
    return matriz_normalizada

def calcular_pesos(matriz_normalizada):
    pesos = np.mean(matriz_normalizada, axis=1)
    return pesos

def calcular_consistencia(matriz, pesos):
    lambda_max = np.mean(np.sum(matriz * pesos, axis=1) / pesos)
    n = matriz.shape[0]
    ci = (lambda_max - n) / (n - 1)
    return ci

def calcular_cr(ci, n):
    ri_dict = {1: 0.00, 2: 0.00, 3: 0.58, 4: 0.90, 5: 1.12, 6: 1.24, 7: 1.32, 8: 1.41, 9: 1.45, 10: 1.49}
    ri = ri_dict.get(n, 1.49)  # Se n > 10, usar 1.49 como valor padrão de RI
    cr = ci / ri
    return cr

# Função principal para AHP
def ahp(matriz_criterios, matrizes_alternativas):
    # Calcular pesos dos critérios
    matriz_criterios_normalizada = normalizar_matriz(matriz_criterios)
    print("matriz_criterios_normalizada: ", matriz_criterios_normalizada)
    pesos_criterios = calcular_pesos(matriz_criterios_normalizada)
    ci_criterios = calcular_consistencia(matriz_criterios, pesos_criterios)
    cr_criterios = calcular_cr(ci_criterios, matriz_criterios.shape[0])

    if cr_criterios > 0.1:
        print(f"A matriz de critérios não é consistente. CR = {cr_criterios:.2f}")

    # Calcular pesos das alternativas para cada critério
    pesos_alternativas = []
    cr_alternativas = []
    for i, matriz in enumerate(matrizes_alternativas):
        matriz_normalizada = normalizar_matriz(matriz)
        print("matriz_normalizada: ", matriz_normalizada)
        pesos = calcular_pesos(matriz_normalizada)
        ci = calcular_consistencia(matriz, pesos)
        cr = calcular_cr(ci, matriz.shape[0])

        if cr > 0.1:
            print(f"Uma das matrizes de alternativas (Critério {i+1}) não é consistente. CR = {cr:.2f}")

        pesos_alternativas.append(pesos)
        cr_alternativas.append(cr)

    # Calcular a pontuação final das alternativas
    pesos_alternativas = np.array(pesos_alternativas).T
    pontuacao_final = np.dot(pesos_alternativas, pesos_criterios)

    return pesos_criterios, cr_criterios, pesos_alternativas, cr_alternativas, pontuacao_final

# Exemplo com 3 critérios e 5 alternativas
matriz_criterios = np.array([
    [1, 1/2, 4],
    [2, 1, 7],
    [1/4, 1/7, 1]
])

matriz_alternativas_c1 = np.array([
    [1, 1/3, 3, 1/2, 2],
    [3, 1, 5, 1/3, 1/4],
    [1/3, 1/5, 1, 1/7, 1/2],
    [2, 3, 7, 1, 4],
    [1/2, 4, 2, 1/4, 1]
])

matriz_alternativas_c2 = np.array([
    [1, 5, 1/7, 3, 1/3],
    [1/5, 1, 1/8, 1/4, 1/5],
    [7, 8, 1, 5, 2],
    [1/3, 4, 1/5, 1, 1/2],
    [3, 5, 1/2, 2, 1]
])

matriz_alternativas_c3 = np.array([
    [1, 2, 1/3, 4, 1/2],
    [1/2, 1, 1/4, 3, 1/3],
    [3, 4, 1, 5, 2],
    [1/4, 1/3, 1/5, 1, 1/7],
    [2, 3, 1/2, 7, 1]
])

matrizes_alternativas = [matriz_alternativas_c1, matriz_alternativas_c2, matriz_alternativas_c3]

# Chamar a função AHP
pesos_criterios, cr_criterios, pesos_alternativas, cr_alternativas, pontuacao_final = ahp(matriz_criterios, matrizes_alternativas)

print("Pesos dos Critérios: ", pesos_criterios)
print("Razão de Consistência dos Critérios (CR): ", cr_criterios)
print("Pesos das Alternativas para cada Critério: \n", pesos_alternativas)
print("Razões de Consistência das Alternativas (CR): ", cr_alternativas)
print("Pontuação Final das Alternativas: ", pontuacao_final)


matriz_criterios_normalizada:  [[0.30769231 0.30434783 0.33333333]
 [0.61538462 0.60869565 0.58333333]
 [0.07692308 0.08695652 0.08333333]]
matriz_normalizada:  [[0.14634146 0.0390625  0.16666667 0.22459893 0.25806452]
 [0.43902439 0.1171875  0.27777778 0.14973262 0.03225806]
 [0.04878049 0.0234375  0.05555556 0.06417112 0.06451613]
 [0.29268293 0.3515625  0.38888889 0.44919786 0.51612903]
 [0.07317073 0.46875    0.11111111 0.11229947 0.12903226]]
Uma das matrizes de alternativas (Critério 1) não é consistente. CR = 0.23
matriz_normalizada:  [[0.0867052  0.2173913  0.07259528 0.26666667 0.08264463]
 [0.01734104 0.04347826 0.06352087 0.02222222 0.04958678]
 [0.60693642 0.34782609 0.50816697 0.44444444 0.49586777]
 [0.02890173 0.17391304 0.10163339 0.08888889 0.12396694]
 [0.26011561 0.2173913  0.25408348 0.17777778 0.24793388]]
matriz_normalizada:  [[0.14814815 0.19354839 0.1459854  0.2        0.1257485 ]
 [0.07407407 0.09677419 0.10948905 0.15       0.08383234]
 [0.44444444 0.38709677 