<a href="https://colab.research.google.com/github/aguilarmadeira/CIO/blob/main/AHP_3criterios_3alternativas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

def normalizar_matriz(matriz):
    soma_colunas = np.sum(matriz, axis=0)
    matriz_normalizada = matriz / soma_colunas
    return matriz_normalizada

def calcular_pesos(matriz_normalizada):
    pesos = np.mean(matriz_normalizada, axis=1)
    return pesos

def calcular_consistencia(matriz, pesos):
    lambda_max = np.mean(np.sum(matriz * pesos, axis=1) / pesos)
    n = matriz.shape[0]
    ci = (lambda_max - n) / (n - 1)
    return ci

def calcular_cr(ci, n):
    ri_dict = {1: 0.00, 2: 0.00, 3: 0.58, 4: 0.90, 5: 1.12, 6: 1.24, 7: 1.32, 8: 1.41, 9: 1.45, 10: 1.49}
    ri = ri_dict.get(n, 1.49)  # Se n > 10, usar 1.49 como valor padrão de RI
    cr = ci / ri
    return cr

# Função principal para AHP
def ahp(matriz_criterios, matrizes_alternativas):
    # Calcular pesos dos critérios
    matriz_criterios_normalizada = normalizar_matriz(matriz_criterios)
    print("matriz_criterios_normalizada: ", matriz_criterios_normalizada)
    pesos_criterios = calcular_pesos(matriz_criterios_normalizada)
    ci_criterios = calcular_consistencia(matriz_criterios, pesos_criterios)
    cr_criterios = calcular_cr(ci_criterios, matriz_criterios.shape[0])

    if cr_criterios > 0.1:
        print(f"A matriz de critérios não é consistente. CR = {cr_criterios:.2f}")

    # Calcular pesos das alternativas para cada critério
    pesos_alternativas = []
    cr_alternativas = []
    for i, matriz in enumerate(matrizes_alternativas):
        matriz_normalizada = normalizar_matriz(matriz)
        print("matriz_normalizada: ", matriz_normalizada)
        pesos = calcular_pesos(matriz_normalizada)
        ci = calcular_consistencia(matriz, pesos)
        cr = calcular_cr(ci, matriz.shape[0])

        if cr > 0.1:
            print(f"Uma das matrizes de alternativas (Critério {i+1}) não é consistente. CR = {cr:.2f}")

        pesos_alternativas.append(pesos)
        cr_alternativas.append(cr)

    # Calcular a pontuação final das alternativas
    pesos_alternativas = np.array(pesos_alternativas).T
    pontuacao_final = np.dot(pesos_alternativas, pesos_criterios)

    return pesos_criterios, cr_criterios, pesos_alternativas, cr_alternativas, pontuacao_final

# Exemplo com 3 critérios e 3 alternativas
matriz_criterios = np.array([
    [1, 1/2, 4],
    [2, 1, 7],
    [1/4, 1/7, 1]
])

matriz_alternativas_c1 = np.array([
    [1, 1/3, 3],
    [3, 1, 5],
    [1/3, 1/5, 1]
])

matriz_alternativas_c2 = np.array([
    [1, 5, 1/7],
    [1/5, 1, 1/8],
    [7, 8, 1]
])

matriz_alternativas_c3 = np.array([
    [1, 2, 1/3],
    [1/2, 1, 1/4],
    [3, 4, 1]
])

matrizes_alternativas = [matriz_alternativas_c1, matriz_alternativas_c2, matriz_alternativas_c3]

# Chamar a função AHP
pesos_criterios, cr_criterios, pesos_alternativas, cr_alternativas, pontuacao_final = ahp(matriz_criterios, matrizes_alternativas)

print("Pesos dos Critérios: ", pesos_criterios)
print("Razão de Consistência dos Critérios (CR): ", cr_criterios)
print("Pesos das Alternativas para cada Critério: \n", pesos_alternativas)
print("Razões de Consistência das Alternativas (CR): ", cr_alternativas)
print("Pontuação Final das Alternativas: ", pontuacao_final)


matriz_criterios_normalizada:  [[0.30769231 0.30434783 0.33333333]
 [0.61538462 0.60869565 0.58333333]
 [0.07692308 0.08695652 0.08333333]]
matriz_normalizada:  [[0.23076923 0.2173913  0.33333333]
 [0.69230769 0.65217391 0.55555556]
 [0.07692308 0.13043478 0.11111111]]
matriz_normalizada:  [[0.12195122 0.35714286 0.11267606]
 [0.02439024 0.07142857 0.09859155]
 [0.85365854 0.57142857 0.78873239]]
Uma das matrizes de alternativas (Critério 2) não é consistente. CR = 0.22
matriz_normalizada:  [[0.22222222 0.28571429 0.21052632]
 [0.11111111 0.14285714 0.15789474]
 [0.66666667 0.57142857 0.63157895]]
Pesos dos Critérios:  [0.31512449 0.6024712  0.08240431]
Razão de Consistência dos Critérios (CR):  0.001708646345928768
Pesos das Alternativas para cada Critério: 
 [[0.26049796 0.19725671 0.23948761]
 [0.63334572 0.06480345 0.13728766]
 [0.10615632 0.73793983 0.62322473]]
Razões de Consistência das Alternativas (CR):  [0.03337472496505753, 0.22498167484776346, 0.015807980379471724]
Pontuaçã